In [15]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors

#get data
tab = '/storage/shared/apollo/same-day/tabular_data.csv'
df_tab = pd.read_csv(tab)
df_tab = df_tab.dropna(subset=['CO'])
labels = list(df_tab['PCWP_mean'])

# PCLR, RHC Representations
pclr_reprs = np.load('pclr.npy') #pt_no, 320dim
rhc_reprs = np.load('/storage/hyewonjeong/RHCnet/rhc.npy') #pt_no, 320dim

k_nb = 2

In [16]:
pclr_nbrs = NearestNeighbors(n_neighbors=k_nb, algorithm='ball_tree').fit(pclr_reprs)
distances, indices = pclr_nbrs.kneighbors(pclr_reprs)

In [17]:
rhc_nbrs = NearestNeighbors(n_neighbors=k_nb, algorithm='ball_tree').fit(rhc_reprs)
distances, indices = rhc_nbrs.kneighbors(rhc_reprs)

In [18]:
indices #original label, indices label 

array([[   0, 1308],
       [   1, 3157],
       [   2, 3837],
       ...,
       [6287, 1615],
       [6288, 5183],
       [6289, 5182]])

In [19]:
indices_labels = np.zeros(np.array(indices).shape)
for i in range(len(indices)):
    for j in range(k_nb):
        indices_labels[i][j] = labels[indices[i][j]]

In [12]:
indices_labels

array([[26., 26.],
       [23., 29.],
       [ 9., 27.],
       ...,
       [ 9., 16.],
       [ 9.,  6.],
       [13.,  6.]])

In [14]:
labels == indices_labels[0]

/storage/hyewonjeong/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [22]:
for i in range(len(labels)):
    if labels[i] != indices_labels[i][1]:
        print(labels[i], indices_labels[i])

23.0 [23. 29.]
9.0 [ 9. 27.]
13.0 [13.  8.]
12.0 [12. 19.]
14.0 [14. 19.]
13.0 [13. 19.]
11.0 [11. 20.]
18.0 [18. 16.]
19.0 [19. 15.]
25.0 [25. 31.]
20.0 [20. 10.]
5.0 [ 5. 24.]
19.0 [19. 17.]
9.0 [ 9. 11.]
17.0 [17.  7.]
9.0 [ 9. 28.]
8.0 [ 8. 22.]
28.0 [28. 26.]
9.0 [ 9. 12.]
29.0 [29. 24.]
8.0 [ 8. 30.]
10.0 [10. 20.]
31.0 [31. 23.]
15.0 [15. 25.]
17.0 [17. 32.]
11.0 [11. 12.]
8.0 [ 8. 14.]
16.0 [16.  8.]
25.0 [25. 18.]
24.0 [24. 10.]
23.0 [23. 12.]
26.0 [26.  5.]
25.0 [25. 13.]
23.0 [23. 16.]
26.0 [26. 20.]
17.0 [17. 26.]
25.0 [25. 28.]
19.0 [19. 24.]
20.0 [20. 25.]
30.0 [30. 10.]
21.0 [21. 16.]
10.0 [10. 11.]
12.0 [12. 10.]
30.0 [30. 23.]
25.0 [25. 11.]
36.0 [36. 19.]
25.0 [25. 23.]
30.0 [30.  7.]
8.0 [ 8. 18.]
18.0 [18. 25.]
22.0 [22.  9.]
27.0 [27.  9.]
20.0 [20. 14.]
25.0 [25. 19.]
16.0 [16. 10.]
19.0 [19. 34.]
28.0 [28. 22.]
10.0 [10. 21.]
12.0 [12.  8.]
18.0 [18. 33.]
22.0 [22. 24.]
20.0 [20. 21.]
14.0 [14. 31.]
20.0 [20. 19.]
17.0 [17. 27.]
13.0 [13.  6.]
27.0 [27.  7.]
9.0 

7.0 [7. 4.]
26.0 [26. 28.]
25.0 [25. 14.]
11.0 [11. 22.]
37.0 [37. 15.]
12.0 [12. 14.]
20.0 [20. 22.]
18.0 [18. 22.]
18.0 [18. 28.]
15.0 [15.  6.]
19.0 [19.  2.]
19.0 [19. 14.]
11.0 [11. 25.]
25.0 [25. 11.]
29.0 [29. 20.]
16.0 [16. 22.]
24.0 [24. 19.]
13.0 [13. 24.]
26.0 [26.  8.]
30.0 [30. 26.]
18.0 [18. 11.]
21.0 [21. 12.]
13.0 [13. 26.]
8.0 [ 8. 18.]
26.0 [26. 13.]
23.0 [23. 26.]
32.0 [32.  9.]
4.0 [ 4. 14.]
5.0 [ 5. 10.]
17.0 [17. 27.]
14.0 [14. 11.]
8.0 [ 8. 27.]
22.0 [22. 11.]
31.0 [31. 26.]
19.0 [19. 12.]
15.0 [15. 12.]
15.0 [15. 14.]
12.0 [12. 25.]
11.0 [11. 19.]
8.0 [8. 5.]
5.0 [ 5. 16.]
14.0 [14.  8.]
7.0 [ 7. 28.]
13.0 [13.  8.]
19.0 [19. 26.]
17.0 [17. 20.]
24.0 [24. 22.]
23.0 [23.  5.]
28.0 [28. 30.]
13.0 [13. 18.]
17.0 [17.  4.]
21.0 [21. 32.]
7.0 [ 7. 14.]
19.0 [19. 12.]
8.0 [ 8. 24.]
6.0 [ 6. 17.]
12.0 [12. 10.]
28.0 [28. 22.]
19.0 [19. 13.]
18.0 [18.  5.]
22.0 [22.  9.]
6.0 [6. 5.]
15.0 [15. 27.]
16.0 [16.  6.]
11.0 [11.  8.]
17.0 [17. 19.]
6.0 [ 6. 13.]
8.0 [ 8. 16.]


26.0 [26. 28.]
11.0 [11. 16.]
9.0 [9. 8.]
10.0 [10. 11.]
18.0 [18. 19.]
4.0 [ 4. 29.]
23.0 [23. 24.]
11.0 [11.  9.]
34.0 [34. 28.]
24.0 [24. 21.]
11.0 [11. 16.]
7.0 [ 7. 20.]
15.0 [15.  7.]
31.0 [31. 26.]
12.0 [12. 13.]
13.0 [13. 14.]
14.0 [14. 13.]
14.0 [14.  7.]
18.0 [18.  9.]
35.0 [35. 16.]
32.0 [32. 12.]
6.0 [ 6. 20.]
38.0 [38. 11.]
30.0 [30. 33.]
19.0 [19. 21.]
12.0 [12. 21.]
29.0 [29. 18.]
10.0 [10. 20.]
37.0 [37. 23.]
18.0 [18. 34.]
24.0 [24. 14.]
25.0 [25. 26.]
20.0 [20. 18.]
38.0 [38.  2.]
9.0 [ 9. 16.]
6.0 [6. 8.]
11.0 [11.  7.]
16.0 [16. 10.]
15.0 [15. 30.]
7.0 [ 7. 29.]
23.0 [23. 11.]
26.0 [26. 18.]
22.0 [22.  7.]
13.0 [13. 12.]
12.0 [12. 13.]
12.0 [12.  9.]
7.0 [ 7. 10.]
9.0 [ 9. 12.]
12.0 [12.  9.]
9.0 [9. 7.]
9.0 [ 9. 13.]
12.0 [12.  9.]
14.0 [14.  9.]
13.0 [13.  9.]
21.0 [21.  4.]
20.0 [20. 10.]
9.0 [ 9. 20.]
6.0 [ 6. 26.]
8.0 [8. 6.]
26.0 [26. 31.]
34.0 [34. 25.]
14.0 [14. 10.]
25.0 [25. 26.]
6.0 [ 6. 28.]
5.0 [ 5. 17.]
5.0 [ 5. 30.]
12.0 [12.  8.]
10.0 [10.  7.]
6.0 [

7.0 [ 7. 15.]
8.0 [ 8. 16.]
13.0 [13. 15.]
15.0 [15. 13.]
4.0 [4. 9.]
7.0 [7. 9.]
14.0 [14. 13.]
8.0 [ 8. 36.]
7.0 [ 7. 11.]
21.0 [21.  5.]
15.0 [15. 14.]
11.0 [11. 14.]
24.0 [24.  9.]
32.0 [32. 18.]
11.0 [11.  8.]
9.0 [ 9. 16.]
11.0 [11. 10.]
8.0 [ 8. 14.]
12.0 [12. 39.]
14.0 [14.  7.]
6.0 [ 6. 12.]
14.0 [14. 19.]
11.0 [11. 13.]
9.0 [9. 7.]
13.0 [13. 30.]
6.0 [ 6. 23.]
30.0 [30. 15.]
35.0 [35.  9.]
35.0 [35.  8.]
7.0 [ 7. 15.]
5.0 [5. 6.]
15.0 [15.  6.]
13.0 [13.  2.]
12.0 [12. 15.]
20.0 [20. 10.]
4.0 [ 4. 16.]
21.0 [21.  8.]
18.0 [18. 15.]
17.0 [17. 16.]
32.0 [32. 17.]
19.0 [19. 15.]
8.0 [ 8. 15.]
13.0 [13. 10.]
26.0 [26. 30.]
31.0 [31. 11.]
8.0 [ 8. 20.]
13.0 [13. 14.]
5.0 [ 5. 16.]
23.0 [23. 18.]
22.0 [22. 11.]
30.0 [30. 12.]
17.0 [17. 24.]
17.0 [17. 12.]
33.0 [33. 30.]
33.0 [33. 19.]
28.0 [28. 17.]
27.0 [27. 12.]
9.0 [ 9. 15.]
15.0 [15. 13.]
36.0 [36. 26.]
16.0 [16. 30.]
15.0 [15. 10.]
17.0 [17. 15.]
12.0 [12. 13.]
15.0 [15. 17.]
15.0 [15.  5.]
12.0 [12. 15.]
30.0 [30. 10.]
26.0 [

9.0 [ 9. 25.]
29.0 [29. 17.]
23.0 [23. 19.]
23.0 [23. 13.]
8.0 [ 8. 11.]
11.0 [11. 20.]
20.0 [20.  8.]
12.0 [12. 10.]
9.0 [ 9. 16.]
14.0 [14. 16.]
13.0 [13.  7.]
28.0 [28. 17.]
21.0 [21. 28.]
22.0 [22. 19.]
30.0 [30. 14.]
18.0 [18.  8.]
7.0 [ 7. 12.]
10.0 [10.  2.]
13.0 [13. 12.]
15.0 [15. 27.]
12.0 [12. 13.]
13.0 [13. 12.]
17.0 [17. 41.]
12.0 [12. 13.]
20.0 [20.  6.]
25.0 [25.  5.]
16.0 [16. 32.]
11.0 [11. 25.]
9.0 [ 9. 12.]
11.0 [11. 18.]
16.0 [16. 18.]
14.0 [14. 26.]
8.0 [ 8. 14.]
15.0 [15. 23.]
23.0 [23. 17.]
17.0 [17. 22.]
16.0 [16. 26.]
29.0 [29.  5.]
14.0 [14. 13.]
24.0 [24. 20.]
12.0 [12. 27.]
9.0 [9. 5.]
6.0 [6. 8.]
8.0 [ 8. 28.]
6.0 [ 6. 15.]
13.0 [13. 21.]
36.0 [36. 14.]
28.0 [28.  8.]
14.0 [14. 20.]
6.0 [6. 8.]
10.0 [10. 19.]
7.0 [ 7. 14.]
13.0 [13. 26.]
16.0 [16. 20.]
18.0 [18. 15.]
14.0 [14. 25.]
9.0 [ 9. 22.]
20.0 [20. 17.]
9.0 [9. 6.]
25.0 [25. 11.]
16.0 [16. 24.]
12.0 [12. 14.]
23.0 [23. 11.]
26.0 [26. 20.]
18.0 [18. 10.]
13.0 [13. 12.]
18.0 [18. 10.]
26.0 [26. 22.]
8.

10.0 [10. 13.]
21.0 [21. 17.]
19.0 [19.  6.]
22.0 [22.  6.]
23.0 [23. 12.]
18.0 [18. 16.]
12.0 [12. 27.]
24.0 [24.  6.]
23.0 [23. 15.]
19.0 [19. 12.]
9.0 [ 9. 11.]
16.0 [16.  9.]
15.0 [15.  8.]
9.0 [ 9. 16.]
7.0 [ 7. 15.]
28.0 [28. 20.]
20.0 [20. 28.]
18.0 [18. 30.]
16.0 [16. 20.]
19.0 [19. 24.]
13.0 [13. 14.]
17.0 [17. 13.]
5.0 [ 5. 30.]
8.0 [ 8. 22.]
8.0 [8. 4.]
6.0 [ 6. 17.]
11.0 [11. 13.]
18.0 [18. 22.]
32.0 [32. 28.]
17.0 [17. 10.]
19.0 [19.  4.]
15.0 [15.  7.]
19.0 [19. 26.]
9.0 [9. 7.]
6.0 [6. 5.]
11.0 [11.  5.]
19.0 [19. 20.]
9.0 [ 9. 13.]
31.0 [31. 34.]
11.0 [11. 17.]
12.0 [12. 17.]
5.0 [ 5. 10.]
5.0 [5. 4.]
9.0 [ 9. 10.]
9.0 [9. 3.]
10.0 [10. 16.]
13.0 [13. 17.]
13.0 [13.  3.]
8.0 [ 8. 12.]
27.0 [27. 21.]
8.0 [ 8. 23.]
5.0 [ 5. 23.]
13.0 [13. 24.]
7.0 [ 7. 15.]
29.0 [29. 25.]
13.0 [13. 11.]
1.0 [1. 3.]
34.0 [34. 29.]
20.0 [20.  4.]
21.0 [21. 13.]
4.0 [4. 7.]
4.0 [4. 6.]
17.0 [17.  6.]
16.0 [16. 15.]
25.0 [25. 11.]
29.0 [29.  3.]
13.0 [13.  9.]
9.0 [9. 8.]
13.0 [13. 27.]
28.0 

In [8]:
np.zeros(np.array(indices).shape)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
type(labels)

pandas.core.series.Series